config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: 'users'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks do
    member do
      post :toggle_status
    end
  end

  devise_scope :user do
    authenticated :user do
      root 'tasks#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  validates :title, :description, presence: true

  enum status: { recently_added: 0, in_progress: 1, done: 2 }

  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, presence: true

  has_many :tasks
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include DeviseWhitelist
end

app/controllers/concerns/devise_whitelist.rb
# frozen_string_literal: true

module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
    devise_parameter_sanitizer.permit(:edit, keys: %i[first_name last_name])
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :find_task, only: %i[edit update destroy toggle_status]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url
  end

  def toggle_status
    if @task.recently_added?
      @task.in_progress!
    elsif @task.in_progress?
      @task.done!
    elsif @task.done?
      @task.recently_added!
    end
    redirect_to tasks_url
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
    <%= yield %>

    <% if current_user.is_a?(User) %>
      <%= link_to "Edit User", edit_user_registration_path %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% end %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<center><h1>Edit Task</h1></center>

<p><center><%= link_to 'All tasks', tasks_path, class: 'btn btn-primary' %></center></p>

<%= form_for(@task) do |f| %>
    <div class="form-text">
      <a<%= f.label 'Title:' %>
      <p></p>
      <%= f.text_field :title %>
    </div>
    <p></p>
    <div class="form-text">
      <%= f.label 'Description:' %>
      <p></p>
      <%= f.text_area :description %>
    </div>
    <p></p>
    <p></p>
    <div class="field">
      <%= f.label 'User:' %>
      <%= f.collection_select :user_id, User.order(:first_name), :id, :first_name %>
    </div>
    <p></p>
    <div class="actions">
      <%= f.submit %>
    </div>
    <p></p>
<% end %>

app/views/tasks/index.html.erb
<center><h1>Tasks</h1></center>

<center><%= link_to "Create new task", new_task_path, class: 'btn btn-primary' %></center>
<p></p>
<div class="row">
  <% @tasks.each do |task| %>
    <div class="col-md-4">
      <div class="card">
        <div class="card-body">
          <p class="card-header"><%= task.title %></p>
          <p class="card-text"><%= task.description %></p>
          <p><%= link_to "Current status: #{task.status}", toggle_status_task_path(task), method: :post, class: 'btn btn-link' %></p>
          <%= link_to "Edit", edit_task_path(task), class: 'btn btn-secondary'%>
          <%= link_to "Delete Task", task_path(task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-secondary' %>
        </div>
      </div>
     </div>         
  <% end %>
</div>   

app/views/tasks/new.html.erb
<center><h1>Create a new Task</h1></center>

<p><center><%= link_to 'All tasks', tasks_path, class: 'btn btn-primary' %></center></p>

<%= form_for(@task) do |f| %>
    <div class="form-text">
      <a<%= f.label 'Title:' %>
      <p></p>
      <%= f.text_field :title %>
    </div>
    <p></p>
    <div class="form-text">
      <%= f.label 'Description:' %>
      <p></p>
      <%= f.text_area :description %>
    </div>
    <p></p>
    <p></p>
    <div class="field">
      <%= f.label 'User:' %>
      <%= f.collection_select :user_id, User.order(:first_name), :id, :first_name %>
    </div>
    <p></p>
    <div class="actions">
      <%= f.submit %>
    </div>
    <p></p>
<% end %>